name: "bbmap-readlength"
description: Generate read length histogram with BBMap readLength.sh
authors:
  - Leandro C. Hermida
notes: |
  * For more information, see https://sourceforge.net/projects/bbmap/
